---
minimum_pre_commit_version: "4.6.1"
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: commitizen
        name: commitizen check
        entry: cz check --allow-abort --message-length-limit=100 --commit-msg-file
        language: python
        additional_dependencies:
          - commitizen==4.17.0
        stages:
          - commit-msg

      - id: documentation-format
        name: documentation uses AsciiDoc
        entry: Markdown documentation is not permitted; use AsciiDoc (.adoc).
        language: fail
        files: (?i)\.(md|markdown)$
